### ISSUE TITLE
PDF with instruction

### ISSUE THREAD

**Issue by agosiewska** [SachaEpskamp/StatcheckTheGame#1]
Hi!
Thank you for this game! The theme is brilliant.
I was testing it today (proof below :) ).
How about creating a pdf with instruction to print and maybe with QR code providing to Statcheck?

![img_20180603_172430](https://user-images.githubusercontent.com/18423383/40888180-ca9f3bb0-6753-11e8-8c54-1d6508732500.jpg)

**Comment by SachaEpskamp** [comment]
Cool! Here is the PDF version of the website: https://github.com/SachaEpskamp/StatcheckTheGame/blob/master/index.pdf. It contains instructions to print the game too. QR code to statcheck is a great idea! I don't know how stable the link is we use now though... it seems it already went over the time shinyapps.io allows.

**Comment by agosiewska** [comment]
Thank you! 
I'm closing this issue :)
